name: Deploy Supabase

on:
  push:
    branches:
      - main  # ou ta branche de prod
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Ta clé d'accès (générée via `supabase login`)
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      # Le project-ref (disponible dans Settings > API de Supabase)
      PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
      # 1) Récupère ton code
      - uses: actions/checkout@v4

      # 2) Installe la CLI Supabase
      - uses: supabase/setup-cli@v1
        with:
          version: latest  # ou un numéro précis, ex. "1.67.4"

      # 3) Déploie ta base de données (migrations)
      - run: supabase db push --project-ref $PROJECT_REF

      # 4) Déploie toutes tes Edge Functions
      - run: supabase functions deploy --project-ref $PROJECT_REF
